{% set name = "cli11" %}
{% set version = "2.1.2" %}
{% set sha_hash = "26291377e892ba0e5b4972cdfd4a2ab3bf53af8dac1f4ea8fe0d1376b625c8cb" %}
{% set build_number = "0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CLIUtils/CLI11/archive/v{{ version }}.tar.gz
  sha256: {{ sha_hash }}

build:
  number: {{ build_number }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    #  libboost is not available in s390x yet. When it is, update `build.sh` to ensure autor's tests are run.
    - libboost >=1.61  # [not s390x]

test:
  # NOTE: Author's tests are run from the build scripts in all architectures (except s390x!).
  commands:
    # Insure files are installed to the correct location.
    - test -f $PREFIX/include/CLI/CLI.hpp  # [unix]
    - if exist %LIBRARY_INC%\CLI\CLI.hpp (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/CLIUtils/CLI11
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: CLI11 is a command line parser for C++11 and beyond that provides a rich feature set with a simple and intuitive interface.
  description: |
    CLI11 provides all the features you expect in a powerful command line
    parser, with a beautiful, minimal syntax and no dependencies beyond
    C++11. It is header only, and comes in a single file form for easy
    inclusion in projects. It is easy to use for small projects, but
    powerful enough for complex command line projects, and can be
    customized for frameworks. It is tested on Travis, AppVeyor, Azure,
    and GitHub Actions, and is used by the GooFit GPU fitting framework.
    It was inspired by plumbum.cli for Python. CLI11 has a user friendly
    introduction in this README, a more in-depth tutorial GitBook, as well
    as API documentation generated by Travis. See the changelog or GitHub
    Releases for details for current and past releases. Also see the
    Version 1.0 post, Version 1.3 post, or Version 1.6 post for more
    information.
  dev_url: https://github.com/CLIUtils/CLI11
  doc_url: https://cliutils.github.io/CLI11/book
  doc_src_url: https://github.com/CLIUtils/CLI11/tree/main/docs

extra:
  recipe-maintainers:
    - wolfv
    - henryiii
